### ISSUE TITLE
Minimize Vaadin dependencies (vaadin10)

### ISSUE THREAD

**Issue by martingr** [berndhopp/guice#20]
The addon has a dependency on the `vaadin` (platform) acrtifact and therefore you also get all transitive depencencies of that artifact when you use this addon in a project. In fact, the addon would only need the `flow-server` and `flow-html-components` dependecies. As a user i would like this addon to come with a minimal set of depenencies to have more control over them. Especially when it comes to the vaadin version I would like to use. As it is now, I always get _all_ depencencies for the latest Vaadin release.

**Comment by martingr** [comment]
After returning to a project after several weeks without active development and with the release of Vaadin 14, the project now fails to build. Because of this addon I'm now forced to either update my project code to Vaadin 14 or to actively exclude the vaadin dependencies it entails. For now, I've decided to opt for the latter option and update later. Due to the way the Vaadin dependency (more specifically the version) is currently handled in this addon, the problem is not unlikely to recur. 

@berndhopp are there any plans to tackle this or what do you think about it in general? What is the reason for having a dynamic version?

**Comment by berndhopp** [comment]
fixed in 2019.1-vaadin14
